networks:
  net-authenticator:
    driver: bridge
services:
  app:
    build: .
    ports: ["3000:3000"]
    env_file: .env
    restart: unless-stopped
    depends_on: [pg-authenticator, redis-authenticator]
    networks:
      - net-authenticator
  pg-authenticator:
    image: bitnami/postgresql:latest
    container_name: pg-authenticator
    environment:
      - POSTGRESQL_USERNAME=${USER_DB}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./data:/bitnami/postgresql
    networks:
      - net-authenticator
  redis-authenticator:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=redis
    ports:
      - 6379:6379
    networks:
      - net-authenticator