export enum SecurityEventType {
  INVALID_LOGIN_ATTEMPT = 'INVALID_LOGIN_ATTEMPT',
  MULTIPLE_IPS_DETECTED = 'MULTIPLE_IPS_DETECTED',
  SIMULTANEOUS_SESSIONS = 'SIMULTANEOUS_SESSIONS',
  MANUAL_TOKEN_REVOCATION = 'MANUAL_TOKEN_REVOCATION',
  PASSWORD_RESET_REQUESTED = 'PASSWORD_RESET_REQUESTED',
  REFRESH_TOKEN_REUSED = 'REFRESH_TOKEN_REUSED',
  OTHER = 'OTHER',
}
